### ISSUE TITLE
Should token descriptions support multiple languages?

### ISSUE THREAD

**Issue by kevinmpowell** [design-tokens/community-group#84] opened 2021-11-16 13:18 UTC
See comments:

https://github.com/design-tokens/community-group/issues/62#issuecomment-956479996

https://github.com/design-tokens/community-group/issues/62#issuecomment-957836722

https://github.com/design-tokens/community-group/issues/62#issuecomment-969385732

**Comment by ChucKN0risK** [comment] 2021-11-16 18:23
Reviewed by the spec editors on 2021-11-16.

Decision
Token descriptions do not support multiple languages.

Why?
This enables the spec:
- be more easily implemented by design tool vendors
- remain as simple as possible 

Action to be taken
We will close this issue and might reopen it in the future.

**Comment by c1rrus** [comment] 2021-11-16 19:54
Just want to add that, for teams that need multiple languages (such as [the Canadian government example](https://github.com/design-tokens/community-group/issues/62#issuecomment-956479996) that @delisma mentioned), the [draft spec's `extensions` property](https://design-tokens.github.io/community-group/format/#extensions) could be a viable alternative for now.

For example, you might create your own extension along these lines to house a 2nd description in another language:

```json
{
  "Button background": {
    "value": "#777777",
    "description": "The background colour for buttons in their normal state.",
    "extensions": {
      "ca.canada.design-system": {
        "description-fr": "La couleur de fond des boutons dans leur état normal."
      }
    }
  }
}
```

Of course, you'd need custom tools / plug-ins to do anything useful with your extension though.

**Closed** 2021-11-16 19:57 UTC
Labels: RFC

**Comment by delisma** [comment] 2021-11-16 23:06
> Reviewed by the spec editors on 2021-11-16.
> 
> **Decision** Token descriptions do not support multiple languages.
> 
> **Why?** This enables the spec:
> 
> * be more easily implemented by design tool vendors
> * remain as simple as possible
> 
> **Action to be taken** We will close this issue and might reopen it in the future.

I'm just concerned that asking tool vendors to add multiple languages support in the spec after it was implemented without it, could add undesired development issues for them on the long run. I feel it should be left to the tools vendors to decide if the implementation is simpler later than now.

@duboisp
@joshbeveridge
