### ISSUE TITLE
Can extensions be applied on the group level?

### ISSUE THREAD

**Issue by natemoo-re** [design-tokens/community-group#106] opened 2022-01-21 03:48 UTC
I've been building [Token CSS](https://github.com/tokencss/tokencss), a CSS tool based on the current draft spec.

I really like the groups can define a `type` which will be applied to all child tokens. I was curious if `extensions` could also be applied to groups? I'm hoping to use `extensions` to define a `scale` ([`semantic-type`](https://github.com/design-tokens/community-group/issues/104) or `used-for` values) on a per-group basis.

I'm not sure there's anything blocking this usage in the current specification but clarity would be nice! I don't think the spec needs to weigh in on how inheritance/cascading of `extensions` could work—that seems like an implementation detail left up to each tool.

Edit: I had not seen that https://github.com/design-tokens/community-group/pull/89 moves group-level properties under the `metadata` name, but I'm a huge fan of that move! I guess my question then becomes "Is `extensions` allowed inside of `group.metadata`?"

**Comment by c1rrus** [comment] 2022-01-25 23:50
(FYI: We've now ditched the `group.metadata` idea in favour of using a `$` prefix for our format-specific properties on groups and tokens.)

Allowing the `$extensions` property on groups as well as tokens seems like a good idea to me - especially if tools like yours already have potential uses for that.

As you've noted, the question to answer is whether it should be an inherited property or not. I'm tempted to say that it should _not_ be inherited - i.e. tokens and groups within a group that has `$extensions` should not be treated as though they themselves had the same `$extensions` property.

`$extensions` is just a container where teams and/or tool vendors can add arbitrary data that has some special meaning to them. If the spec mandates that it is inherited like `$type` is, it would be imposing additional behaviour on anything people put inside `$extensions`. _However_, there's nothing stopping a tool from implementing some logic to make its own extensions behave like inherited properties.

So rather than forcing all extensions to be inherited, my preference would be to say they're not. But tool vendors are welcome to implement their own inheritence behaviour for their own extensions if they wish.

**Comment by lauthieb** [comment] 2022-07-01 00:03
@natemoo-re +1, could be nice to be able to set `$extensions` property at group level.

**Comment by CITguy** [comment] 2022-11-08 00:23
> As you've noted, the question to answer is whether it should be an inherited property or not. I'm tempted to say that it should _not_ be inherited - i.e. tokens and groups within a group that has `$extensions` should not be treated as though they themselves had the same `$extensions` property.

I agree that `$extensions` should _not_ be inherited, because if it were, we'd then have to define how inheritance is applied if `$extensions` exists at deeper levels of the JSON tree.  Additionally, we'd also have to figure out if/how `$extensions` would be resolved with token aliases, too.

**Comment by iammerrick** [comment] 2022-11-27 21:19
Was just coming here to indicate that I felt Group's should support `$extensions` as well. If Design Tools are able to augment the spec with additional metadata using `$extensions`, we'd be unable to store any additional information for groups as the spec currently stands. 

A common case for us would better help data... I realize the spec has "$description" but often a lot more (structured) data is leveraged by design tools to link to resources.

**Comment by lauthieb** [comment] 2022-11-27 21:23
@iammerrick +1 !

**Closed** 2023-07-16 15:44 UTC
Labels: Needs Feedback/Review, dtcg-format
